format: "[QQ群]%user%: §6%msg%"
imageFormat: "[§6图片§f]"
imageHover: "§6点击查看"
#游戏发送到群
GameToGroup: "%player_name%: %msg%"
At:
  title: " "
  subTitle: "§7你被§6 %player% §7@了,注意一下聊天栏吧"
# 不需要输入qq send 即可同步聊天消息到群
GameChatToGroup:
  Enable: false
  groups:
    - "123456"
MessageGroup:
  - '123456'
Message:
  Join: "%player_name% 加入了服务器"
  Quit: "%player_name% 离开了服务器"
  Death: "%player_name% 在服务器中惨遭死亡"